
#Explicação tratamento das colunas vazias

l = ['TIPO','ID','CNPJ/CPF','RAZÃO SOCIAL','FORMA DE PAGAMENTO ','BANCO','AGENCIA','CONTA','TIPO DE CONTA','NATUREZA DA CONTA',
'VALOR','VALOR PAGO','DATA SOLICITADA PARA PAGAMENTO','DATA DA SOLICITAÇÃO ','DATA DE PAGAMENTO','COMENTÁRIO ROBO','AJUSTE','STATUS SGP','DATA DE EXECUÇÃO ROBO']

l[11] = ','
l[16] = ','


l2 = ['PRODUTO CONTÁBIL','DATA DE EMISSÃO','TIPO DO DOCUMENTO','NUMERO DE NOTA FISCAL','NATUREZA CONTÁBIL','CENTRO DE CUSTO','DATA EFETIVA DE VENCIMENTO','RATEIO','CONDIÇÃO DE PAGAMENTO','DATA DE LANCAMENTO NO TOTVS','MÓDULO','COLABORADOR SGP','COLABORADOR TOTVS','COMENTÁRIO FINANCEIRO','STATUS FINANCEIRO','DATA EFETIVA DE PAGAMENTO'] #18-26



#11 =,
#15 =,

for x in range(18):
    l.append(',')

print(l)
print(len(l))